# permissions for end users to view foobars.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: foobar-viewer-role
rules:
- apiGroups:
  - apps.undeadops.xyz
  resources:
  - foobars
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.undeadops.xyz
  resources:
  - foobars/status
  verbs:
  - get
