apiVersion: apps.undeadops.xyz/v1alpha1
kind: FooBar
metadata:
  name: undead
  namespace: barx
  annotations:
    prometheus.io/scrap: "true"
    prometheus.io/port: "9797"
  labels:
    owner: "sre"
spec:
  replicas: 2
  foo:
    pod:
      image: ghcr.io/stefanprodan/podinfo:6.1.6
      ports:
        - name: http
          containerPort: 9898
          protocol: TCP
        - name: http-metrics
          containerPort: 9797
          protocol: TCP
        - name: grpc
          containerPort: 9999
          protocol: TCP
      command:
        - ./podinfo
        - --port=9898
        - --port-metrics=9797
        - --grpc-port=9999
        - --grpc-service-name=podinfo
        - --level=info
        - --random-delay=false
        - --random-error=false
      env:
        - name: PODINFO_UI_COLOR
          value: "#34577c"
      resources:
        limits:
          cpu: 2000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 64Mi
    ingress:
      servicePort: 9898
      ingressClassName: traefik
